name: build

on: [push]
env:
  app-path: ./Test/App
  sln-name: ./Test.sln
  version: 0.6.13
jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    # OpenSiv3D セットアップ
    - name: Setup s3d
      run: |
        bitsadmin /transfer s3d-download "https://siv3d.jp/downloads/Siv3D/manual/${{ env.version }}/OpenSiv3D_SDK_${{ env.version }}.zip" "C:\OpenSiv3D_SDK.zip"
        Expand-Archive -Path "C:\OpenSiv3D_SDK.zip" -DestinationPath "C:"
      shell: powershell
    # ビルド
    - name: MSBuild
      run: |
        $s3dVersion = "${{ env.version }}"
        $s3dVersionEnv = "SIV3D_" + $s3dVersion.Replace('.', '_')        
        msbuild ${{env.sln-name}} -p:Configuration=Release;Platform="x64";SIV3D_0_6_13="C:\OpenSiv3D_SDK_${{ env.version }}"
      shell: powershell
    # ビルド結果をアップロード
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: ${{env.app-path}}

