name: build

on: [push]
env:
  sln-name: Test.sln
  cache-version: v1

jobs:
  build:
    name: MSBuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: MSBuild
      run: msbuild ${{env.sln-name}} -p:Configuration=Debug;Platform="x64"
      shell: cmd
